# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: helm-resources

builds:
  - id: default
    main: .
    binary: bin/resources
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X github.com/sergelogvinov/helm-resources/cmd.Version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    ids:
      - default
    formats: ["tgz"]
    name_template: '{{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: resources
    files:
      - README.md
      - plugin.yaml
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: checksum
    certificate: "${artifact}.pem"
    cmd: cosign
    args:
      - sign-blob
      - "--yes"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    output: true
